print('=' * 5, 'TESTE-01', '=' * 5)
nome = input('Qual o seu nome? ')
idade = input('Qual sua idade? ')
peso = input('Qual seu peso? ')
print('Olá {}! Você está aprendendo a programar aos {} anos e tem {}kg.'.format(nome, idade, peso))
print('Vamos ver o quanto vai engordar. kkk')
