print('=' * 5, 'TESTE-02', '=' * 5)
dia = int(input('DIA: '))
mes = int(input('MÊS: '))
ano = int(input('ANO: '))
print('Você nasceu no dia em {}/{}/{}.'.format(dia, mes, ano))
print('=' * 5, 'SOMA', '=' *5)
n1 = input('Primeiro número: ')
n2 = input('Segundo número: ')
soma = int(n1) + int(n2)
print("A soma é: ", soma)
