print('=' * 5, 'EX_000', '=' * 5)
print('-' * 5, 'Parte 1\n')
nome = input('Qual é o seu nome?\n')
print('Olá ', nome, '! Bom te ver por aqui!')
print('-' * 5, 'Parte 2\n')
dia = input('DIA: ')
mes = input('MÊS: ')
ano = input('ANO: ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano, '.\nCerto?')
print('-' * 5, 'Parte 3')
print('Informe dois números inteiros.')
n1 = input('Primeiro número: ')
n2 = input('Segundo número: ')
s = int(n1) + int(n2)
print('A soma é:\n', s)
